apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-microservice
  template:
    metadata:
      labels:
        app: go-microservice
    spec:
      containers:
        - name: go-microservice
          image: localhost:5000/my-go-microservice:latest # Update this if you're using a different image name
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: go-microservice-service
spec:
  type: NodePort
  ports:
    - port: 8080           # Port that the service listens on
      targetPort: 8080     # Port that the container listens to
      nodePort: 30001      # Change this to a valid NodePort
  selector:
    app: go-microservice
