apiVersion: v1
kind: Service
metadata:
  name: go-microservice-service
  namespace: simple-microservice-project
spec:
  type: NodePort
  ports:
    - port: 8080           # Port that the service listens on
      targetPort: 8080     # Port that the container listens to
      nodePort: 30001      # Change this to a valid NodePort
  selector:
    app: go-microservice
