apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: simple-microservice-project
data:
  fluent.conf: |
    <source>
      @type tail
      path /var/log/*.log
      pos_file /var/log/fluentd.pos
      tag kube.*
      <parse>
        @type json
      </parse>
    </source>

    <match kube.**>
      @type elasticsearch
      host elasticsearch
      port 9200
      logstash_format true
      logstash_prefix kubernetes
      logstash_dateformat %Y.%m.%d
      include_tag_key true
      type_name _doc
    </match>
