apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-microservice
  namespace: simple-microservice-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-microservice
  template:
    metadata:
      labels:
        app: go-microservice
    spec:
      containers:
        - name: go-microservice
          image: localhost:5000/my-go-microservice:latest # Update this if you're using a different image name
          ports:
            - containerPort: 8080
